name = "markshift"
compatibility_date = "2026-02-05"

[[routes]]
pattern = "markshift.net"
custom_domain = true

[[routes]]
pattern = "www.markshift.net"
custom_domain = true

[assets]
directory = "./dist"
not_found_handling = "single-page-application"
